test data

diff --git a/.github/workflows/pull-requests.yml b/.github/workflows/pull-requests.yml
--- a/.github/workflows/pull-requests.yml
+++ b/.github/workflows/pull-requests.yml
@@ -33,5 +33,16 @@ jobs:
         run: |
           git fetch origin main
           URLS=$(git diff origin/main..HEAD --unified=0 -- ./data/members.json | grep '"url"'  | grep -o '\"url\":\s\".*\"' | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u)
-          chmod +x ./workflows/pull-request.sh
-          sh ./workflows/pull-request.sh
+          for url in $URLS; do\
+            echo "Looking at $url"\
+            curl -s $url | grep -qo "<the-claw-webring-widget>"\
+            if [ $? -eq 0 ]; then\
+              echo "The <the-claw-webring-widget> tag was found in $url"\
+            else\
+              echo "The <the-claw-webring-widget> tag was not found in $url"\
+              exit -1\
+            fi\
+          done\
+          \
+          echo "Finished searching for and it passed"\
+          exit 0\
